# Generated by Django 5.2.5 on 2025-08-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spots", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spot",
            old_name="quietness",
            new_name="quiet_level",
        ),
    ]
