# Generated by Django 5.2.5 on 2025-08-25 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spots", "0002_rename_quietness_spot_quiet_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spot",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
