# Generated by Django 5.2.5 on 2025-08-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spots", "0004_alter_spot_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="spot",
            name="slug",
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True),
        ),
    ]
