# Generated by Django 5.2.5 on 2025-08-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0005_spot_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='slug',
            field=models.SlugField(max_length=160, unique=True),
        ),
    ]
