services:
  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: dev-secret
      DJANGO_SETTINGS_MODULE: core.settings_dev
    volumes:
      - .:/app
