[tool.black] 
line-length = 100 
target-version = ["py311","py312"] 
 
[tool.ruff] 
line-length = 100 
target-version = "py312" 
fix = true

[tool.ruff.lint]
select = ["E","F","I","UP","B"] 
ignore = ["E501"]
